server:
  port: 8762

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zhangdianyang/MyProject.git
          search-paths: /SpringCloudConfig/{application}
          username: zhangdianyang
          password: zdy1991227
      label: master
      enabled: true
      name: ${spring.application.name},zdy
  application:
    name: config-server

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


